### PR TITLE
Ledger support - updated

### PR DESCRIPTION
**Pull request by pinheadmz**
Closes https://github.com/kyokan/bob-wallet/pull/266

This is an updated Ledger integration branch. The device app itself as well as the client have been updated. Ledger released a new SDK for the Nano S and also released an entirely new device (the Nano X) which we had to support. After working on the device app code for a few weeks I've discovered a few more bells and whistles we can add to the Bob Wallet integration.

Summary of changes:

- @mslipper's original Ledger PR from November 2020
- rebased on master (biggest update since November is multi-wallet support)
- added new features:
  - automatically verify change outputs inside the device app without user review
  - support HIP-0004 interactive atomic swaps with device signing single-reverse
- clean up:
  - use a smaller modal and marginalize it so TX details are still visible in Bob UI while verifying on the device
  - fixed on-boarding flow with Ledger
  - show/hide device errors in modals
  - cancel Ledger confirmation if wallet locks / timeout
 
NOTE: Shakedex is currently disabled for Ledger wallets for now.

### To review

Even before Ledger releases our app into production, you can build it yourself and load it on to your own device. The device will work on both regtest and mainnet. I have been using Docker on OSX to build and load the app, but Linux users can follow the directions in the [README](https://github.com/handshake-org/ledger-app-hns#linux-install) if they want to build it on their native system. Keep in mind Ledger requires a special ARM compiler and a few python dependencies, so I just recommend using Docker.

Note: The version of the HNS app on Ledger live (version 1.0.3) has a bug that was fixed in v1.0.4. Until this version is approved by Ledger and added to their system, you MUST build the app from the latest source code.

```
# SDK required for the Makefile but is re-cloned in Docker anyway
git clone https://github.com/LedgerHQ/nanos-secure-sdk 
cd nanos-secure-sdk
git checkout nanos-1612
export BOLOS_SDK=`pwd`
cd ..

# Python3 stuff required to push final app to device
pip install virtualenv
virtualenv ledger
source ledger/bin/activate
pip install ledgerblue
pip install Pillow

# Device app codebase
git clone https://github.com/handshake-org/ledger-app-hns
cd ledger-app-hns
git checkout s-x-compat

# connect your Ledger Nano S via USB, enter your PIN and quit any open Ledger apps

make docker-load
```

### Virtual Nano X

It is also possible to test a virtual Nano X using [Speculos](https://github.com/LedgerHQ/speculos). I can add instructions to this comment if anyone is really interested -- the Ledger client can redirect message packets from USB to a TCP connection by setting the environment variable `export SPECULOS=true` before running Bob in dev mode.

### Demonstration

[Ledger hardware wallet integration into Bob Wallet for Handshake](https://www.youtube.com/watch?v=CJCCE7enL2E "Ledger hardware wallet integration into Bob Wallet for Handshake")

### TODO

- [x] The button to create new Ledger wallet is visible even if an existing one exists. It fails in the background, but can be hidden/disabled I think.
- [x] "Reveal recovery seed phrase" in Settings -> Wallet asks for passphrase when there isn't any, blank doesn't work.
- [x] For GitHub CI to pass, busb needs libusb-dev libudev-dev installed on ubuntu. May even need to update readme with this.
- [x] Check device xpub matches bob account before continuing signature flow

### CODE REVIEW

**Comment by Falci** [comment]
That is great @pinheadmz!

I'm testing it locally, using the version 1.0.3 of Handshake app for Nano S.

I'd like to suggest a small UX improvement: clear the error messages.
To reproduce:
* Unplug the ledger.
* Make a transfer in Bob.
* It will ask to plug and continue, don't plug and just click connect.
* It fails, with the correct error message.
* Now connect the Ledger and enter the PIN.
* On Bob, click on connect again.

Bob will be in a loading/waiting state but the previous errors are still visible.
image

This is not a blocker at all.

**Comment by Falci** [comment]
I spot something else: there's no password.

It's a bit obvious, because the TX will be signed by the external device. However, Bob used to ask for password even to show portfolio or domain manager.
In other words: a person in front of my computer can't open my Bob and see my data without the password.

I believe Bob don't have password manager and just uses `hsw-cli` to validate the passphrase, and I suppose this is the main reason why the ledger'ed wallet don't have the password field on login page.

We could request the device even for unlocking Bob. I'm personally against it.
We could, instead, open an issue, asking Bob to support other means to lock/unlock the account, not only `hsw-cli`.
This is not a blocker for this PR, but we should warn the users that, at least temporary, the accounts using Ledger will not be lockable.

**Comment by pinheadmz** [comment]
@Falci thanks! Error handling is improved in: 900d3915e5919d9d8ac5085dc1f3907c84211183

Basically, the Ledger modal should handle and display all errors while the background just waits (forever) either for a confirmation from the device OR the user clicking the "cancel" button, which returns us to the main wallet UI with a "Cancelled" error. This also displays verbose errors from the device, like if the user cancels on the device itself or if something actually goes wrong in the device app itself.

RE: Passwords, yeah - [I had the same reaction](https://github.com/kyokan/bob-wallet/pull/266#discussion_r516640080) Seems like we should do something, but it can be a follow-up PR.

I agree the device should not be required to just unlock the portfolio and get receive addressees, etc - I think maybe we could just add a  hashed `ledger-password` field in the DB and a UI function to change it in settings. The password hash could maybe be salted by the accounts xpub or something...

**Comment by rithvikvibhu** [comment]
Awesome work, a lot of people have been waiting for this :p

A couple of things I noticed, nothing really serious:
- The button to create new Ledger wallet is visible even if an existing one exists. It fails in the background, but can be hidden/disabled I think.
- "Reveal recovery seed phrase" in Settings -> Wallet asks for passphrase when there isn't any, blank doesn't work.

Also had a question about what happens if you connect a different ledger device once Bob is using one already? Bob monitors an xpub that's only communicated once (I think), so signing probably won't work. Tried to test this with 2 different speculos containers, but both could sign successfully, maybe because they are from the same image and have the same key?

image
image

**Comment by Falci** [comment]
All my tests worked fine.

ACK 72bdd2ac5fef70e1a276fb54b26951758a2ba683
<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK 72bdd2ac5fef70e1a276fb54b26951758a2ba683
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEa1BPNxzSHCYYRcK6SAB/zAtFvWsFAmCjeJUACgkQSAB/zAtF
vWuqShAAl1FAexAtYVxVcdhZsZ5g9UTiGDeFpuGR9AdkppZ3ZbvYuAJSaVWFU0Jg
01H2GWQaUIQyJQbZ7ZHCvnnqXjUwQAs3NCxBV8Mo+KmVrUJpzh4bK9+s3XDOWyLn
DKrU/mgMH9G1kLuXWma3c96i8WknhG3G5XL76DMR4HNHDmMPOkRvjp4aJlhh11lO
XuWWWBHSmkhvS3uo30ZzQF6V7fftXF3pvnQAsdmYci7UqNv8HD8/nrHvh/RN62q2
cE/DKpnhN3x9b7jppzNVHx0Js7PUWMRpUVhQ6oDzx4tAHPwvbsrFxdZ2aZ+CodfW
0C2KCJArSgeEHA6z9Axz7ImYoZhtTZHTen2pJ+d1fFraC8jGLgMbiLcukLeXfO73
0ek5eZRA/sOBHJnR+18v3aYtngEXyv8ia16Cp8X8RebG9taX7o9ggt6GYmYq7zg6
Q9QLpNSMHImgwsMtIWSuf7ihCSL/A538pfT4daWOxc/CqNVjhQgk2x3ReM5356Zw
8uK5iYMwB27IkGJKw8MGg7YT22F1d/h4FSA0uNAN+098r8IHMUSRorobLMUJZXQH
zsENw0d6KGDPnGUUqquH2/Bi03RQj+r1nhtBn9squ54dqhfLm0ngyj/QmE6X0EPn
Y2PUYrLDmMW7QBBfGy3cLTQ8zWnxUPq6GbUWqoUo2xsOPYC1/Zw=
=Q75n
-----END PGP SIGNATURE-----
```

falci's public key is [on keybase](https://keybase.io/falci/pgp_keys.asc?fingerprint=6dc8c6b244885baa4ad98806fce9edc1105b4db4)
</details>

**Comment by chikeichan** [comment]
@pinheadmz Just tested this on `simnet` - i can verify that `send`, `open`, `bid`, `reveal`, `transfer`, `finalize with payment`, and `claim name with payment` work!

Going to merge this in for now, but before release `0.8.0`, i would like to get the following done:
- Add multiple ledger support. It hardcodes wid to `Ledger` right now, i think we can allow user to set wid and use the same onboarding flow - this should address the `xpub` check @rithvikvibhu mentioned
- Add password to ledger wallets (should be same as existing flow) - @Falci 's suggestion
- Disabled `Reveal Seedphrase` - I don't think ledger allow you to see seedphrase after onboarding with ledger live
- Fix Github CI - no idea what's wrong, but without this fixed the build will probably fail on Linux.
- Test code on window and Fix if necessary

**Comment by chikeichan** [comment]
Oh, and put ledger feature before a flag in setting, and default it to off.

Until ledger app is official.

**Comment by Falci** [comment]
> Fix Github CI - no idea what's wrong, but without this fixed the build will probably fail on Linux.

Done [here](https://github.com/pinheadmz/bob-wallet/pull/3).

**Comment by pinheadmz** [comment]
Bob will now require the device to have app version 1.0.4 installed.



Screen Shot 2021-05-24 at 11 02 18 AM




I added npm package `semver` to process this, normally I wouldn't add another dependency, but it's already installed for a dozen other packages:

```
--> npm list semver
bob-wallet@0.7.1 /Users/matthewzipkin/Desktop/work/bob-wallet
├─┬ @babel/cli@7.13.16
│ └─┬ make-dir@2.1.0
│   └── semver@5.7.1 
├─┬ @babel/core@7.14.0
│ ├─┬ @babel/helper-compilation-targets@7.13.16
│ │ └── semver@6.3.0 
│ └── semver@6.3.0 
├─┬ @babel/preset-env@7.12.0
│ ├─┬ core-js-compat@3.11.1
│ │ └── semver@7.0.0 
│ └── semver@5.7.1 
├─┬ canvas@2.7.0
│ └─┬ node-pre-gyp@0.15.0
│   └── semver@5.7.1 
├─┬ concurrently@4.1.0
│ └─┬ read-pkg@4.0.1
│   └─┬ normalize-package-data@2.5.0
│     └── semver@5.7.1 
├─┬ cross-env@5.2.0
│ └─┬ cross-spawn@6.0.5
│   └── semver@5.7.1 
├─┬ electron@9.1.1
│ └─┬ @electron/get@1.12.4
│   ├─┬ global-agent@2.2.0
│   │ └── semver@7.3.5 
│   └── semver@6.3.0 
├─┬ electron-builder@22.7.0
│ ├─┬ app-builder-lib@22.7.0
│ │ └── semver@7.3.5 
│ └─┬ update-notifier@4.1.3
│   ├─┬ configstore@5.0.1
│   │ └─┬ make-dir@3.1.0
│   │   └── semver@6.3.0 
│   ├─┬ latest-version@5.1.0
│   │ └─┬ package-json@6.5.0
│   │   └── semver@6.3.0 
│   └─┬ semver-diff@3.1.1
│     └── semver@6.3.0 
├─┬ electron-devtools-installer@2.2.4
│ └── semver@5.7.1 
├─┬ electron-updater@4.1.2
│ └── semver@6.3.0 
├─┬ enzyme-adapter-react-16@1.15.6
│ ├─┬ enzyme-adapter-utils@1.14.0
│ │ └── semver@5.7.1 
│ └── semver@5.7.1 
├─┬ node-sass@4.13.1
│ └─┬ node-gyp@3.8.0
│   └── semver@5.3.0 
├─┬ sass-loader@7.1.0
│ └── semver@5.7.1 
├── semver@7.3.5 
└─┬ webpack-dev-server@3.8.0
  └── semver@6.3.0 
```

**Comment by magicstone1412** [comment]
I have tried to build the latest Bob wallet on Linux with ***node v12.22.1*** but when running ***npm run dev*** it was hung out at the below screen

photo_2021-06-10_21-48-39

Error: Using polyfills: No polyfills were added, since the useBuiltIns option was not set.

I have no problem with @pinheadmz's repo `https://github.com/pinheadmz/bob-wallet.git` branch ledger1

Please improve in the next version. Thank you.

P/S:

I also got some warning below 

```
npm WARN babel-eslint@10.0.1 requires a peer of eslint@>= 4.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN chai-as-promised@7.1.1 requires a peer of chai@>= 2.1.2 < 5 but none is installed. You must install peer dependencies yourself.
npm WARN hsd-ledger@1.0.0-rc2 requires a peer of hsd@git+https://github.com/handshake-org/hsd#semver:^2.1.5 but none is installed. You must install peer dependencies yourself.
npm WARN react-test-renderer@16.14.0 requires a peer of react@^16.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
and others 

```
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

**Pull request merged**
