### PR TITLE
allow custom rpc to switch network type + cache namehash to minimize request to node

### PR DESCRIPTION
**Pull request by chikeichan**
relates to #188

### CODE REVIEW

**Comment by sdtsui** [comment]
proptypes fail when clicking import "import wallet" for the first time in dev

Screen Shot 2020-10-28 at 5 38 22 PM

**Comment by sdtsui** [comment]
another one inbetween step 2 and 3 when creating pw
Screen Shot 2020-10-28 at 5 42 27 PM

**Review by sdtsui — COMMENTED** [review]
@chikeichan  - QA complete.  Apart from the create issue discussed in person, and assorted proptypes 'onStart' (if you care), this is gtg to me.

@pinheadmz - if you have time, a once over would be helpful since you've been thinking about custom rpc stuff since the feature was conceived, `Roberto!` has it, etc. Thanks!

**Comment by chikeichan** [comment]
@sdtsui both error message + the create new account bug is fixed 27de837

**Comment by pinheadmz** [comment]
@sdtsui heres my hack to read port assignments from ENV: https://github.com/pinheadmz/bob-wallet/commit/6f730d60b8c2c3911c995c012d24467a863bcdc7

I'm using the same params as hsd itself, could be better. What would be really great is if we could access a config file as well. It's a little tricky because hsd doesn't run in the shell, but maybe Bob could require [bcfg](https://github.com/bcoin-org/bcfg) and then pass the parsed options to hsd internally.

**Pull request merged**
