### PR TITLE
Added Catalan language, Spanish (Spain) language and XXX.json file.

### PR DESCRIPTION
**Pull request by faltrum**
The internationalization of Bob Wallet in version 0.9.0 has been a very important step with the i18n. A new stage is opened so that members of the community can contribute their grain of sand without being professional developers, simply by translating Bob-Wallet into their mother tongue. However, it will be a challenge to put order and do the translation systematically so as not to repeat processes and waste time.

XXX.json file
For this reason, the creation of the XXX.json file is very important, since it is very easy to check which phrases, words have not yet been included in the en.json file. The following steps are proposed:
1.- Load the XXX.json file in Bob-Wallet to detect what is missing to add to the en.json
2.- New lines to be translated in en.json are added. And a specific period of days is opened to carry out the translation and upload the files by the translators.
3.-Then these new lines are also added to the XXX.json file, in this way the translators will be able to detect which lines have been added quickly, without having to check one by one.

On the other hand, I propose the creation of a file called Terminology (located in the LOCALES folder), to specify the meanings of certain technical words in order to translate them correctly into other languages.
Thank you.

### CODE REVIEW

**Comment by rithvikvibhu** [comment]
Going through the app in different languages feels like a new app :p nice work @faltrum!

I like the XXXX idea. Doesn't have to be in the UI dropdown, and helps find strings that need to be extracted. Found a few using this method: https://github.com/kyokan/bob-wallet/issues/454

>I propose the creation of a file called Terminology (located in the LOCALES folder), to specify the meanings of certain technical words in order to translate them correctly into other languages.

This would help not just translators, but anyone new to Handshake / Bob Wallet. Instead of the locales folder, how about the Wiki https://github.com/kyokan/bob-wallet/wiki? Would be easy to read for everyone, and markdown is rendered properly along with images, etc. that may be needed to explain the terms.

I think we can merge this PR once those last few strings are added from #454. Do you want to add them? Or I can extract strings, then you can add in ES and CAT. Either way is fine

**Comment by faltrum** [comment]
> Going through the app in different languages feels like a new app :p nice work @faltrum!
> 
> I like the XXXX idea. Doesn't have to be in the UI dropdown, and helps find strings that need to be extracted. Found a few using this method: #454
> 
> > I propose the creation of a file called Terminology (located in the LOCALES folder), to specify the meanings of certain technical words in order to translate them correctly into other languages.
> 
> This would help not just translators, but anyone new to Handshake / Bob Wallet. Instead of the locales folder, how about the Wiki https://github.com/kyokan/bob-wallet/wiki? Would be easy to read for everyone, and markdown is rendered properly along with images, etc. that may be needed to explain the terms.
> 
> I think we can merge this PR once those last few strings are added from #454. Do you want to add them? Or I can extract strings, then you can add in ES and CAT. Either way is fine

**Comment by rithvikvibhu** [comment]
@faltrum I've rebased and added new strings to `ca.json` and `es-ES.json` (all blank values right now). Can you add transalations for these fields also?

```
[*] === Locale: ca.json ===

Strings missing from ca.json (to be added):
  "balanceSpendable": "",
  "balanceTotal": "",
  "currentHash": "",
  "currentHeight": "",
  "headingBrowseDomains": "",
  "headingClaimAirdropName": "",
  "headingDomainManager": "",
  "headingExchange": "",
  "headingPortfolio": "",
  "headingReceive": "",
  "headingSend": "",
  "headingSettings": "",
  "headingSignMessage": "",
  "headingVerifyMessage": "",
  "headingWatching": "",
  "headingYourBids": "",
  "miscellaneous": "",
  "openingTextWaitForBidding": "",
  "searchInputPlaceholder": "",
  "searchYourBids": "",
  "settingAPIKeyDesc": "",
  "topLevelDomains": "",
  "transactionHistory": "",
  "walletID": "",


[*] === Locale: es-ES.json ===

Strings missing from es-ES.json (to be added):
  "balanceSpendable": "",
  "balanceTotal": "",
  "currentHash": "",
  "currentHeight": "",
  "headingBrowseDomains": "",
  "headingClaimAirdropName": "",
  "headingDomainManager": "",
  "headingExchange": "",
  "headingPortfolio": "",
  "headingReceive": "",
  "headingSend": "",
  "headingSettings": "",
  "headingSignMessage": "",
  "headingVerifyMessage": "",
  "headingWatching": "",
  "headingYourBids": "",
  "miscellaneous": "",
  "openingTextWaitForBidding": "",
  "searchInputPlaceholder": "",
  "searchYourBids": "",
  "settingAPIKeyDesc": "",
  "topLevelDomains": "",
  "transactionHistory": "",
  "walletID": "",
```

Also added a script that compares for differences in english and other language files (run `npm run check-all-locales` to see above output).

**Comment by faltrum** [comment]
> @faltrum I've rebased and added new strings to `ca.json` and `es-ES.json` (all blank values right now). Can you add transalations for these fields also?
> 
> ```
> [*] === Locale: ca.json ===
> 
> Strings missing from ca.json (to be added):
>   "balanceSpendable": "",
>   "balanceTotal": "",
>   "currentHash": "",
>   "currentHeight": "",
>   "headingBrowseDomains": "",
>   "headingClaimAirdropName": "",
>   "headingDomainManager": "",
>   "headingExchange": "",
>   "headingPortfolio": "",
>   "headingReceive": "",
>   "headingSend": "",
>   "headingSettings": "",
>   "headingSignMessage": "",
>   "headingVerifyMessage": "",
>   "headingWatching": "",
>   "headingYourBids": "",
>   "miscellaneous": "",
>   "openingTextWaitForBidding": "",
>   "searchInputPlaceholder": "",
>   "searchYourBids": "",
>   "settingAPIKeyDesc": "",
>   "topLevelDomains": "",
>   "transactionHistory": "",
>   "walletID": "",
> 
> 
> [*] === Locale: es-ES.json ===
> 
> Strings missing from es-ES.json (to be added):
>   "balanceSpendable": "",
>   "balanceTotal": "",
>   "currentHash": "",
>   "currentHeight": "",
>   "headingBrowseDomains": "",
>   "headingClaimAirdropName": "",
>   "headingDomainManager": "",
>   "headingExchange": "",
>   "headingPortfolio": "",
>   "headingReceive": "",
>   "headingSend": "",
>   "headingSettings": "",
>   "headingSignMessage": "",
>   "headingVerifyMessage": "",
>   "headingWatching": "",
>   "headingYourBids": "",
>   "miscellaneous": "",
>   "openingTextWaitForBidding": "",
>   "searchInputPlaceholder": "",
>   "searchYourBids": "",
>   "settingAPIKeyDesc": "",
>   "topLevelDomains": "",
>   "transactionHistory": "",
>   "walletID": "",
> ```
> 
> Also added a script that compares for differences in english and other language files (run `npm run check-all-locales` to see above output).

Prefect, thanks. I prefer with the words inside and no in blank, better for me to translate, easier to  copy and paste words to differents tools and translate them.

**Review by rithvikvibhu — APPROVED** [review]
Tested, lgtm

**Comment by rithvikvibhu** [comment]
Thanks @faltrum for the translations and other changes!

**Pull request merged**
