### PR TITLE
Add homebrew install method for macOS in README.md

### PR DESCRIPTION
**Pull request by nlydv**
Hey all, I made a Homebrew cask for Bob wallet just for myself to use, but I figured I'd submit it to the main homebrew/cask repo. They merged the PR ([link](https://github.com/Homebrew/homebrew-cask/pull/100309)) which makes it really simple to install now for Mac users.

It's under the name `kyokan-bob` though I originally figured `bob-wallet` would've been a lot better (there's already a cask named bob). The strict naming standards they have wanted it to be based off the actual app's name once installed (i.e. a cask for 'Bob.app' gets the name '[vendor]-bob' when just 'bob' is already in use).

Anyways, this PR only changes the README.md to add that info via a new macOS section under the installation how-to header. There's also a `--zap` stanza in the cask file as well to make it easier to do a complete uninstall as is recommended for certain release upgrades, so I added that info there too.

Let me know if there's anything that should be changed (in the README or the actual Homebrew cask).

### CODE REVIEW

**Comment by pinheadmz** [comment]
Wow this is super cool! Will it require maintenance, ie. updates to homebrew with each new bob release?

**Comment by nlydv** [comment]
> Will it require maintenance, ie. updates to homebrew with each new bob release?

I'm not entirely sure to be honest. My assumption is that if you do `brew upgrade` it will find the latest version but otherwise get whatever version is specified in the file.

Though all you'd have to modify there is the version number and the hash of the .dmg (or .app ? Can't remember) for the new that release:
```
cask "kyokan-bob" do
  version "0.6.2"
  sha256 "5619[...]" 
```

**Comment by nlydv** [comment]
Rebased and also elaborated on details for using `brew`.

A PR to [homebrew/homebrew-cask](https://github.com/homebrew/homebrew-cask) is required to update the brew cask after every new release. Doing so requires running `brew bump-cask-pr --version <VERSION> kyokan-bob` and that PR automatically gets opened (if there actually is a newer release) and is populated with the right info, which anyone with homebrew installed can do ([ex](https://github.com/Homebrew/homebrew-cask/pull/118497)).

Going to open a different PR with a workflow job that can do that automatically whenever a new release gets published. If that works out, I suppose the blockquoted note added in this PR could be removed.

**Review by rithvikvibhu — APPROVED** [review]

**Comment by NetOpWibby** [comment]
Verified this working on an M1 Mac.

**Comment by rithvikvibhu** [comment]
Separated uninstall into its own section since your text applies to Windows and Linux too.

Thanks @nlydv!

**Comment by IAmScottCarlson** [comment]
Just attempted to brew install on a MBP, M1 Pro, Ventura 13.2.1 and no joy.
anyone else have it working ?

**Pull request merged**
