### PR TITLE
Explorer selection

### LINKED ISSUE #152: [Feature] HNScan alternative
I had a look on the HNScan project and decided to run it on my node.
I'd like to configure it on Bob. When I click in a transaction, it should open in my custom HNScan.

### LINKED ISSUE #201: Dial to select block explorer in Settings
@chikeichan

### PR DESCRIPTION
**Pull request by rithvikvibhu**
Closes #201, Closes #152.

This PR adds a dropdown selection for selecting the explorer used to open transactions.
All known explorers are listed, defaults to HNScan.

image
image

## Future work
- Opening names on explorers
- Custom explorers with URL templates

### CODE REVIEW

**Comment by rithvikvibhu** [comment]
Currently, changing the explorer works and the transactions open as expected. But this change doesn't persist when Bob closes and open again. I've looked at how custom RPC is stored and retrieved, but not sure where the code for storing explorer selection should go.

Maybe in `app/background/node/service.js`? This is not strictly a NodeService kind of field though. Or do you think a new file for general settings would be better?

**Comment by chikeichan** [comment]
> Currently, changing the explorer works and the transactions open as expected. But this change doesn't persist when Bob closes and open again. I've looked at how custom RPC is stored and retrieved, but not sure where the code for storing explorer selection should go.
> 
> Maybe in `app/background/node/service.js`? This is not strictly a NodeService kind of field though. Or do you think a new file for general settings would be better?

Thanks for the PR @rithvikvibhu !

I think writing those in `app/background/setting/service` would make sense -- there are likely other things we'd like to persist like you suggest.

**Comment by rithvikvibhu** [comment]
>I think writing those in app/background/setting/service would make sense

Done, and it seems to work. Let me know if anything needs to change.

**Comment by rithvikvibhu** [comment]
Also, how do you feel about this link for the name too?
image

**Comment by pinheadmz** [comment]
My 2 cents: hnscan is not as reliable as it once was and is not under as regular maintenance as hnsnetwork.com

**Comment by rithvikvibhu** [comment]
Hm. Wanna change the default to another one (if so, which)?

**Comment by pinheadmz** [comment]
> Hm. Wanna change the default to another one (if so, which)?

http://hnsnetwork.com/ is my suggestion but as long as there is a way to choose I'm not picky

**Comment by chikeichan** [comment]
reviewed + qa all block explorers. Also pushed a commit to update default to HNSNetwork.

LGTM!

**Review by chikeichan — APPROVED** [review]

**Pull request merged**
